[package]
name = "pyseud2eq"
version = "2.2.0"
authors = ["stale <redkugelblitzin@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
lalrpop-util = "0.19.6"
regex = "1"

[dependencies.rug]
version = "1.14"
default-features = false
features = ["float"]
