[package]
name = "pyseud2eq"
version = "0.1.0"
authors = ["stale <redkugelblitzin@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19.5"

[dependencies]
lalrpop-util = "0.19.5"
regex = "1"
